import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "./main/navbar";
import { AuthProvider } from "@/context/AuthContext";

    const poppins = Poppins({
      subsets: ['latin'],
      display: 'swap',
      variable: '--font-poppins', 
      weight: ['400', '700'] 
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <AuthProvider>
        <Navbar />
        {children}          
        </AuthProvider>
      </body>
    </html>
  );
}
