import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "./main/navbar";
import { AuthProvider } from "@/context/AuthContext";
import Sidebar from "./main/sidebar";

    const poppins = Poppins({
      subsets: ['latin'],
      display: 'swap',
      variable: '--font-poppins', 
      weight: ['400', '700'] 
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <div className="flex min-h-screen overflow-hidden">
            <Sidebar />
            <div className="flex flex-col flex-1">
              <Navbar />
              <main className="flex-1 overflow-hidden">
                {children}
              </main>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
