import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "./main/navbar";

    const poppins = Poppins({
      subsets: ['latin'],
      display: 'swap',
      variable: '--font-poppins', 
      weight: ['400', '700'] // Specify weights if not using a variable font
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
